from .profiler_agent import profiler_agent, ProfilerAgent
from .cleaning_agent import cleaning_agent, CleaningAgent
from .eda_agent import eda_agent, EDAAgent
from .stats_agent import stats_agent, StatisticalAnalysisAgent
from .viz_agent import viz_agent, VisualizationAgent
from .ml_agent import ml_agent, MLAgent
from .insight_agent import insight_agent, InsightGenerationAgent
from .report_agent import report_agent, ReportGenerationAgent
from .supervisor import supervisor_agent, SupervisorAgent
