import datetime
from typing import Dict, Any, List
from models.schemas import ReportGenerateResponse

class ReportGenerationAgent:
    """
    Agent for generating comprehensive executive reports in Markdown and HTML.
    """

    @classmethod
    def generate_report(
        cls,
        dataset_name: str,
        profile_data: Dict[str, Any],
        eda_data: Dict[str, Any],
        custom_title: str = None
    ) -> ReportGenerateResponse:
        now_str = datetime.datetime.now().strftime("%B %d, %Y - %H:%M UTC")
        title = custom_title or f"Executive Data Intelligence Report: {dataset_name}"
        
        row_count = profile_data.get("row_count", 0)
        col_count = profile_data.get("column_count", 0)
        quality = profile_data.get("quality_score", {}).get("overall_score", 100)
        grade = profile_data.get("quality_score", {}).get("grade", "A")
        
        top_corrs = eda_data.get("top_correlations", [])
        key_obs = eda_data.get("key_observations", [])

        # Build Markdown Document
        md_lines = [
            f"# {title}",
            f"**Generated:** {now_str} | **Dataset:** `{dataset_name}` | **Quality Score:** {quality}/100 (Grade {grade})\n",
            "---",
            "## 1. Executive Summary",
            f"This comprehensive data intelligence report provides an automated analytical evaluation of **{dataset_name}**, "
            f"comprising **{row_count:,} records** and **{col_count} attributes**. "
            f"The overall data health is rated **{quality}/100 ({grade})** with an estimated data completeness of "
            f"**{profile_data.get('quality_score', {}).get('completeness_score', 100)}%**.\n",
            "### Core Key Performance Indicators",
            f"- **Total Records:** {row_count:,}",
            f"- **Total Columns:** {col_count}",
            f"- **Memory Footprint:** {profile_data.get('memory_usage_kb', 0)} KB",
            f"- **Duplicate Rows:** {profile_data.get('duplicate_rows_count', 0)} ({profile_data.get('duplicate_rows_percentage', 0)}%)",
            "\n---",
            "## 2. Dataset Schema & Quality Audit",
            "| Column Name | Inferred Type | Missing Count | Missing % | Distinct Values | Outlier Count |",
            "|---|---|---|---|---|---|"
        ]

        for col in profile_data.get("columns", []):
            md_lines.append(
                f"| `{col.get('name')}` | {col.get('inferred_type')} | {col.get('null_count')} | "
                f"{col.get('null_percentage')}% | {col.get('distinct_count')} | {col.get('outlier_count') or 0} |"
            )

        md_lines.extend([
            "\n---",
            "## 3. Exploratory Data Analysis & Key Drivers",
            "### Statistical Observations",
        ])
        for obs in key_obs:
            md_lines.append(f"- {obs}")

        if top_corrs:
            md_lines.extend([
                "\n### Top Linear Associations (Pearson r)",
                "| Feature 1 | Feature 2 | Correlation (r) | Strength |",
                "|---|---|---|---|"
            ])
            for corr in top_corrs[:8]:
                md_lines.append(f"| `{corr.get('col1')}` | `{corr.get('col2')}` | **{corr.get('correlation')}** | {corr.get('strength').replace('_', ' ').title()} |")

        md_lines.extend([
            "\n---",
            "## 4. Strategic Recommendations & Action Plan",
            "1. **Continuous Data Quality Monitoring**: Implement automated validation checks on ingestion pipelines to preserve the current data grade.",
            "2. **Feature Engineering**: Leverage the strong correlations identified above for predictive modeling and segmentation.",
            "3. **Targeted Optimization**: Focus resources on high-impact cohorts to maximize operational return and mitigate churn.",
            "\n---",
            "*Report automatically generated by Agentic AI Data Analysis and Visualization Assistant.*"
        ])

        markdown_content = "\n".join(md_lines)

        # Generate sleek HTML version
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #1e293b; max-width: 900px; margin: 40px auto; padding: 0 20px; background: #f8fafc; }}
        .container {{ background: #ffffff; padding: 40px; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.06); }}
        h1 {{ color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 16px; font-size: 26px; }}
        h2 {{ color: #2563eb; margin-top: 32px; font-size: 20px; }}
        h3 {{ color: #334155; font-size: 16px; }}
        .badge {{ display: inline-block; padding: 4px 12px; border-radius: 9999px; font-weight: bold; background: #dbeafe; color: #1d4ed8; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 14px; }}
        th, td {{ padding: 10px 14px; text-align: left; border-bottom: 1px solid #e2e8f0; }}
        th {{ background-color: #f1f5f9; color: #475569; }}
        tr:hover {{ background-color: #f8fafc; }}
        .kpi-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin: 20px 0; }}
        .kpi-card {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; text-align: center; }}
        .kpi-val {{ font-size: 22px; font-weight: bold; color: #0f172a; margin-top: 4px; }}
        .kpi-label {{ font-size: 12px; color: #64748b; text-transform: uppercase; }}
        ul {{ padding-left: 20px; }}
        li {{ margin-bottom: 8px; }}
        .footer {{ margin-top: 40px; text-align: center; font-size: 13px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 20px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{title}</h1>
        <p><strong>Generated:</strong> {now_str} &nbsp;|&nbsp; <strong>Quality Score:</strong> <span class="badge">{quality}/100 (Grade {grade})</span></p>
        
        <h2>1. Executive Summary</h2>
        <p>Automated intelligence summary for <strong>{dataset_name}</strong> encompassing <strong>{row_count:,} rows</strong> and <strong>{col_count} attributes</strong>.</p>
        
        <div class="kpi-grid">
            <div class="kpi-card"><div class="kpi-label">Total Rows</div><div class="kpi-val">{row_count:,}</div></div>
            <div class="kpi-card"><div class="kpi-label">Total Columns</div><div class="kpi-val">{col_count}</div></div>
            <div class="kpi-card"><div class="kpi-label">Quality Score</div><div class="kpi-val">{quality}%</div></div>
            <div class="kpi-card"><div class="kpi-label">Duplicate Rows</div><div class="kpi-val">{profile_data.get('duplicate_rows_count', 0)}</div></div>
        </div>

        <h2>2. Key Exploratory Findings</h2>
        <ul>
            {"".join(f"<li>{obs}</li>" for obs in key_obs)}
        </ul>

        <h2>3. Strategic Recommendations</h2>
        <ol>
            <li>Implement continuous data validation checks to prevent drift and preserve high data quality scores.</li>
            <li>Incorporate high-correlation features into downstream machine learning models.</li>
            <li>Segment anomalous cohorts to uncover niche business opportunities.</li>
        </ol>

        <div class="footer">
            Report automatically generated by <strong>Agentic AI Data Analysis and Visualization Assistant</strong>
        </div>
    </div>
</body>
</html>"""

        sections = [
            {"title": "Executive Summary", "status": "completed"},
            {"title": "Data Schema & Quality Audit", "status": "completed"},
            {"title": "Exploratory Data Analysis", "status": "completed"},
            {"title": "Strategic Recommendations", "status": "completed"}
        ]

        return ReportGenerateResponse(
            report_title=title,
            generated_at=now_str,
            executive_summary=f"Automated intelligence report for {dataset_name}. Quality Score: {quality}/100.",
            quality_score=quality,
            sections=sections,
            markdown_content=markdown_content,
            html_content=html_content
        )

report_agent = ReportGenerationAgent()
